### ISSUE TITLE
standby error

### ISSUE THREAD

**Issue by dorianeydx** [dhleong/ps4-waker#111]
```
/opt/node/bin $ sudo node ps4-waker standby
WAKEUP sent to device... 192.168.1.4
Logging in...
Error logging in: { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
Error: No socket
    at _this11._waker.wake (/opt/node/lib/node_modules/ps4-waker/dist/device.js:519:38)
    at Ps4Socket.socket.once.on.e (/opt/node/lib/node_modules/ps4-waker/dist/waker.js:366:5)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Socket.client.on.err (/opt/node/lib/node_modules/ps4-waker/dist/ps4socket.js:160:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at onwriteError (_stream_writable.js:417:12)
    at onwrite (_stream_writable.js:439:5)
    at _destroy (internal/streams/destroy.js:39:7)
```

```
$ node -v
v8.15.1
```

```
$ npm -v
6.4.1
```

**Comment by dhleong** [comment]
How did you install `ps4-waker`? That invocation looks weird. You shouldn't be using `node ps4-waker`—in fact, I'm not sure how that's even working. Make sure you install with `npm i -g ps4-waker`, then you can just run as `ps4-waker` by itself. The `sudo` is only required for the initial set-up, after which you should probably not use `sudo`—some people have run into problems there.

That said, the error you're seeing means we were able to locate the device, but due to some network error the socket connection used to send commands like `standby` "broke." I don't recall running into this before, but it's possible the above will fix this. If not, it could be a network issue. Another possibility is that it's a login issue: when you use `ps4-waker` to wake the device, does it login completely, or does it just open to the "press PS button to continue" screen?

Some possibly-relevant troubleshooting sections:

https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#error-device-didnt-wake-in-time

https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#your-network-is-dropping-udp-packets

**Comment by dorianeydx** [comment]
ps4-waker has been installed with `npm i -g ps4-waker` I think it comes from the login, look that
```
pi@raspberrypi:/opt/node/bin $ node ps4-waker -d 192.168.1.4
Device must be awake for initial registration. Please turn it on manually and try again.
pi@raspberrypi:/opt/node/bin $ sudo node ps4-waker -d 192.168.1.4
WAKEUP sent to device... 192.168.1.4
Logging in...
Error logging in: { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
Error: No socket
    at _this11._waker.wake (/opt/node/lib/node_modules/ps4-waker/dist/device.js:519:38)
    at Ps4Socket.socket.once.on.e (/opt/node/lib/node_modules/ps4-waker/dist/waker.js:366:5)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Socket.client.on.err (/opt/node/lib/node_modules/ps4-waker/dist/ps4socket.js:160:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at onwriteError (_stream_writable.js:417:12)
    at onwrite (_stream_writable.js:439:5)
    at _destroy (internal/streams/destroy.js:39:7)
pi@raspberrypi:/opt/node/bin $ sudo node ps4-waker -d 192.168.1.4 --skip-login
WAKEUP sent to device... 192.168.1.4
```

and I just noticed that the app second screen does not work anymore and when I had configure ps4-waker he connected me directly to my account but now it's more the case

so I think we could try to redo the configuration

**Comment by dhleong** [comment]
Have you tried running as just `ps4-waker` instead of `node ps4-waker`? Please also check out the troubleshooting links I provided last time, especially with respect to your use of sudo. 

Have you had any luck redoing the configuration?

If the second screen app doesn't work either then there's something wrong with your network setup, probably. `ps4-waker`'s functionality is based on that of the second screen app, so it is unlikely to work if the official app doesn't.

**Comment by dorianeydx** [comment]
I redo Node install and now it's okay

**Comment by dorianeydx** [comment]
I redo Node install and now it's okay
