### ISSUE TITLE
[BUG]_this2.logError is not a function

### ISSUE THREAD

**Issue by ahjsrhj** [dhleong/ps4-waker#116]
This error occurred when it could not find PS4，
```
$ ps4-waker
/usr/local/lib/node_modules/ps4-waker/dist/cli/base.js:80
          _this2.logError(err.message);
                 ^

TypeError: _this2.logError is not a function
    at detectorFunction (/usr/local/lib/node_modules/ps4-waker/dist/cli/base.js:80:18)
    at Detector.findWhen (/usr/local/lib/node_modules/ps4-waker/dist/detector.js:157:5)
    at Detector.onTimeout (/usr/local/lib/node_modules/ps4-waker/dist/detector.js:120:7)
    at Detector.emit (events.js:193:15)
    at Detector.close (/usr/local/lib/node_modules/ps4-waker/dist/detector.js:93:8)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
```

**Comment by dhleong** [comment]
Thanks for reporting this! Should be fixed in 1.8.3, just released
