### ISSUE TITLE
Login connect refused;

### ISSUE THREAD

**Issue by glad4enkonm** [dhleong/ps4-waker#126]
Having this problem:

sudo npx ps4-waker
```
WAKEUP sent to device... 192.168.1.165
Logging in...
Login connect refused; retrying soon
Login connect refused; retrying soon
Login connect refused; retrying soon
Login connect refused; retrying soon
Error logging in: { Error: connect ECONNREFUSED 192.168.1.165:997
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.165',
  port: 997 }
Unexpected error Error: No socket
    at _this11._waker.wake (/usr/local/lib/node_modules/ps4-waker/dist/device.js:561:38)
    at Ps4Socket.socket.once.on.e (/usr/local/lib/node_modules/ps4-waker/dist/waker.js:374:5)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Socket.client.on.err (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:164:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by dhleong** [comment]
Has it ever worked? Have you tried without sudo? Have you gone through
https://github.com/dhleong/ps4-waker/wiki/Troubleshooting ?

**Comment by glad4enkonm** [comment]
Can not connect with PS4 second screen (when ps4 in rest mode) too "Cannot connect to the PS4 within the time limit", probbably some router problem. Can turn off with second screen, but can not turn it on.

**Comment by dhleong** [comment]
See:
https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#ps4-waker-can-put-the-ps4-to-sleep-but-not-wake-it-up

**Comment by AdamZA1** [comment]
I'm now having the same error but the opposite problem... the PS4 will wake up but won't sleep!
