### ISSUE TITLE
Issue while wake up

### ISSUE THREAD

**Issue by kurtslayer17** [dhleong/ps4-waker#146]
Hi!,

Everything was working properly since one day it doesn't. I could wake up the PS4 but I couldn't shut it down. I have this error:

Error logging in: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
Unexpected error Error: No socket
    at /usr/local/lib/node_modules/ps4-waker/dist/device.js:563:38
    at Ps4Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/waker.js:376:5)
    at Ps4Socket.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:164:10)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

I've tried reinstalling it but can't manage to work, any idea why this error happens?

Thanks in advance! awesome plug in by the way ;)

**Comment by dhleong** [comment]
That sounds a lot like https://github.com/dhleong/ps4-waker/issues/142, which was caused by Sony breaking things. Can you successfully use the official PS4 Second Screen app on your phone to shut down the PS4?

**Comment by kurtslayer17** [comment]
Thanks for quick response! 

Yes, it’s exactly the same issue (sorry for duplicate 😅), second screen app does not detect the PS4 either, but it does detect PS4-Waker, but nothing happens. I’m not sure if I have any PS4 update, I’ll check and let see if that solves the problem!

**Comment by dhleong** [comment]
Good luck! Unfortunately if the official app is broken then we'll be
broken, too. I can't see any way around it.

**Comment by kurtslayer17** [comment]
No worries! It's all fixed now, it was the update... 

Thanks again!
