### ISSUE TITLE
Start title feature causes socket error

### ISSUE THREAD

**Issue by predakanga** [dhleong/ps4-waker#42]
When attempting to use the start title feature (`ps4-waker start CUSA00127`), the PS4 wakes up and starts the title perfectly, but ps4-waker then exits with the following stack trace:
```
WAKEUP sent to device... 192.168.1.41
Logging in...
/opt/node-v6.10.3-linux-armv6l/lib/node_modules/ps4-waker/dist/ps4socket.js:304
    this.client.write(buffer);
               ^

TypeError: Cannot read property 'write' of null
    at Ps4Socket.write (/opt/node-v6.10.3-linux-armv6l/lib/node_modules/ps4-waker/dist/ps4socket.js:304:16)
    at Packet.send (/opt/node-v6.10.3-linux-armv6l/lib/node_modules/ps4-waker/dist/packets.js:126:12)
    at Ps4Socket._ (/opt/node-v6.10.3-linux-armv6l/lib/node_modules/ps4-waker/dist/ps4socket.js:387:53)
    at Ps4Socket.receiveData (/opt/node-v6.10.3-linux-armv6l/lib/node_modules/ps4-waker/dist/ps4socket.js:264:48)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

This occurs both when the PS4 is in standby and when it's awake before issuing the command.

Environment:
PS4-Waker: 1.2.1
PS4 System: 04550011
Node: 6.10.3 (linux armhf) and 7.2.1 (OS X intel)

**Comment by dhleong** [comment]
Thanks for the report! Should be fixed in 1.2.2
