### ISSUE TITLE
app not staring

### ISSUE THREAD

**Issue by shep89** [dhleong/ps4-waker#47]
Hello.
I am using raspbian

```
## Installed:
# apt-get install nodejs npm
## linked:
# ln -s /usr/bin/nodejs /usr/bin/node
## node version:
# node -v
v0.10.29
## starting app
# ps4-waker
/usr/local/lib/node_modules/ps4-waker/bin/cmd.js:3
var {Detector, Device, Socket} = require('../')
    ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

What am i doing wrong?

**Comment by shep89** [comment]
my fail with node version
