### ISSUE TITLE
SyntaxError on raspberry with latest nodejs

### ISSUE THREAD

**Issue by Tezzlicious** [dhleong/ps4-waker#49]
sudo ps4-waker:

/usr/local/lib/node_modules/ps4-waker/bin/cmd.js:3
var {Detector, Device, Socket} = require('../')
    ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Was working fine before general updates. Anyone else experiencing the same problem?

**Comment by dhleong** [comment]
What version of nodejs are you using? Min is now the LTS 6.0

**Comment by Tezzlicious** [comment]
what version is "sudo node -v" reporting?

**Comment by Tezzlicious** [comment]
Nevermind, it was indeed an installation issue with node.
