### ISSUE TITLE
How to work?. PS4 OS 4.7

### ISSUE THREAD

**Issue by qoli** [dhleong/ps4-waker#52]
```
root@FriendlyELEC:~# ps4-waker search 
{
  "type": "device",
  "statusLine": "620 Server Standby",
  "statusCode": "620",
  "status": "Standby",
  "host-id": "1234567890AB",
  "host-type": "PS4",
  "host-name": "PS4-Waker",
  "host-request-port": "997",
  "device-discovery-protocol-version": "00020020",
  "address": "192.168.1.104"
}
```
```
root@FriendlyELEC:~# ps4-waker
Device must be awake for initial registration. Please turn it on manually and try again.

root@FriendlyELEC:~# ps4-waker --pin 18629938
Device must be awake for initial registration. Please turn it on manually and try again.

root@FriendlyELEC:~# ps4-waker --pin 18629938 -d 192.168.1.28
No credentials; Use Playstation App and try to connect to PS4-Waker
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:987
    at Object.exports._errnoException (util.js:1014:11)
    at exports._exceptionWithHostPort (util.js:1037:20)
    at _handle.lookup (dgram.js:242:18)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

```
```
root@FriendlyELEC:~# ps4-waker --pin 18629938 -b 192.168.1.28
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRNOTAVAIL 192.168.1.28
    at Object.exports._errnoException (util.js:1014:11)
    at exports._exceptionWithHostPort (util.js:1037:20)
    at _handle.lookup (dgram.js:242:18)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

```
root@FriendlyELEC:~# node -v
v8.1.0
root@FriendlyELEC:~# npm -v
5.0.3

```

so, someone can tell me how to work?
thx.

**Comment by dhleong** [comment]
> Device must be awake for initial registration. Please turn it on manually and try again.

This means you have to manually turn on the PS4 and try again. The search result shows it was in standby.
