### ISSUE TITLE
SyntaxErrors with version 1.2.0 and above.

### ISSUE THREAD

**Issue by RobotLimeLtd** [dhleong/ps4-waker#53]
I can't run version 1.2.0.  Without getting errors.  I'm running on a Raspberry Pi 3 with Node 4.8.3 - what's the minimum version of Node supported for these versions?

Fortunately, I'm able to restore functionality by downgrading to version 1.1.0

The error I get for version 1.2.0 is:

```
/usr/lib/node_modules/ps4-waker/bin/cmd.js:86
        let waker = d._waker();
        ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

For versions 1.2.1 - 1.3.3, the error is:

```
/usr/lib/node_modules/ps4-waker/bin/cmd.js:3
var {Detector, Device, Socket} = require('../')
    ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by dhleong** [comment]
https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#syntaxerror-unexpected-token-error
