### ISSUE TITLE
encryptionSchemeProvider is undefined

### ISSUE THREAD

**Issue by thibmaek** [dhleong/ps4-waker#55]
When trying to set up the authentication with the app the following exception occurred.
Tried reinstalling the module globally already.

- Device: Raspberry Pi B+ (arm)
- Node version: 6.11.0
- ps4-waker version: 1.3.3
- Expected: It tries to authenticate with the ps4 app and ask for pincode
- Output:
```
$ sudo ps4-waker
WAKEUP sent to device... 192.168.0.x
Logging in...
/usr/local/lib/node_modules/ps4-waker/node_modules/node-rsa/src/libs/rsa.js:79
            this.signingScheme = this.encryptionScheme = encryptionSchemeProvider.makeScheme(this, options);
                                                                                 ^

TypeError: Cannot read property 'makeScheme' of undefined
    at RSAKey.module.exports.Key.RSAKey.setOptions (/usr/local/lib/node_modules/ps4-waker/node_modules/node-rsa/src/libs/rsa.js:79:82)
    at NodeRSA.module.exports.NodeRSA.setOptions (/usr/local/lib/node_modules/ps4-waker/node_modules/node-rsa/src/NodeRSA.js:148:22)
    at new NodeRSA (/usr/local/lib/node_modules/ps4-waker/node_modules/node-rsa/src/NodeRSA.js:80:14)
    at Object.createPublicKey (/usr/local/lib/node_modules/ps4-waker/dist/ps4lib.js:95:16)
    at PacketFactory.newHandshakePacket (/usr/local/lib/node_modules/ps4-waker/dist/packets.js:221:32)
    at Ps4Socket._ (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:362:32)
    at Ps4Socket.receiveData (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:278:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```

**Comment by dhleong** [comment]
Wow, that is bizarre! 

When you reinstall, are you completely deleting the `/usr/local/lib/node_modules/ps4-waker` directory first? It looks like there's something weird going on with the `node-rsa` module that we depend on, but that thing literally hasn't changed in months....

Other than the above, here's a few ideas to try to figure out what's going on:

- Open `/usr/local/lib/node_modules/ps4-waker/node_modules/node-rsa/package.json` and look for `"version": "<SOMETHING>"`; please report the `<SOMETHING>` part. It should be `0.4.2`.
- Open `/usr/local/lib/node_modules/ps4-waker/node_modules/node-rsa/src/schemes/schemes.js` and verify that it looks the same as [this](https://github.com/rzcoder/node-rsa/blob/c8c81345e49e50ab04bee760d88404aeb26cbc98/src/schemes/schemes.js) It should.

If that all checks out, I'll need you to do some exploring for me since I can't reproduce it locally.

1. In `/usr/local/lib/node_modules/ps4-waker/node_modules/node-rsa/src/` on line 148, there should be:

```javascript
        this.keyPair.setOptions(this.$options);
```

Just above that, insert:
```javascript
        console.log(this.$options.encryptionSchemeOptions);
        console.log(Object.keys(schemes));
```

Then, run it again and report the output.

**Comment by thibmaek** [comment]
Seems like `npm uninstall -g ps4-waker` didn't completely delete the module.
Forcibly deleting the folder at `/usr/local/lib/node_modules/ps4-waker` and reinstalling with `npm install -g ps4-waker` worked.

**Comment by dhleong** [comment]
Glad to hear it's working!
