### ISSUE TITLE
Raspberry Pi  app doesn't start 

### ISSUE THREAD

**Issue by LOCOSP** [dhleong/ps4-waker#59]
root@raspberrypi:~# ps4-waker

/usr/local/lib/node_modules/ps4-waker/bin/cmd.js:3
var {Detector, Device, Socket} = require('../')
    ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
root@raspberrypi:~# node -v
v0.10.29
root@raspberrypi:~# 

any ideas ?

**Comment by dhleong** [comment]
https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#syntaxerror-unexpected-token-error

Your version of node is very old.
