### ISSUE TITLE
Root permissions required to start PS4 Dummy

### ISSUE THREAD

**Issue by rourke** [dhleong/ps4-waker#76]
I installed ps4-waker as user pi and when I'm running ps4-waker for the first time it gives the following errors:

```
No credentials; Use the PS4 Second Screen App and try to connect to PS4-Waker
Error: Root permissions required to start PS4 Dummy
    at Dummy.listen (/home/pi/.nvm/versions/node/v8.9.4/lib/node_modules/ps4-waker/dist/dummy.js:48:28)
    at Waker.requestCredentials (/home/pi/.nvm/versions/node/v8.9.4/lib/node_modules/ps4-waker/dist/waker.js:222:11)
    at Device.d.on (/home/pi/.nvm/versions/node/v8.9.4/lib/node_modules/ps4-waker/bin/cmd.js:262:20)
    at emitOne (events.js:116:13)
    at Device.emit (events.js:211:7)
    at Waker.__waker.Waker.on.d (/home/pi/.nvm/versions/node/v8.9.4/lib/node_modules/ps4-waker/dist/device.js:498:18)
    at emitOne (events.js:116:13)
    at Waker.emit (events.js:211:7)
    at /home/pi/.nvm/versions/node/v8.9.4/lib/node_modules/ps4-waker/dist/waker.js:129:18
    at ReadFileContext.callback (/home/pi/.nvm/versions/node/v8.9.4/lib/node_modules/ps4-waker/dist/waker.js:168:29)
```

I did the connection part. The Second Screen app is connected. So I assume it actually needs root permission and it has nothing to do with the credentials? I also noticed `dummy.js` states that it needs root permission for it to run on port 987. So I'm doing `sudo ps4-waker` but it returns the error:

`sudo: ps4-waker: command not found`

Which makes sence because I didn't install it as root. How do I go from here?

**Comment by rourke** [comment]
Didn't notice the Wiki Troubleshoot page.

I moved `/root/.ps4-wake.credentials.json` to `~/.ps4-wake.credentials.json` and now it works great. Love the program!

For learning purpose I wonder what I should've done differently. Could you (@dhleong) perhaps answer this? :)

**Comment by dhleong** [comment]
I honestly don't know since I don't have a raspberry pi, but its `sudo` must work differently than on macOS. For me, `sudo ps4-waker` still creates the credentials file in my user home directory, so when I subsequently run without it, it still works. You are correct that root privileges are only required to bind to port 987, and that is only required as part of the process of getting user credentials.
