### ISSUE TITLE
Error WAKE UP

### ISSUE THREAD

**Issue by eukiseioh** [dhleong/ps4-waker#79]
i can standby ps4 but i can't wake up. Show this error when send wake up command:

`WAKEUP sent to device... 192.168.0.127
Error: Device didn't wake in time
    at loop (/usr/local/lib/node_modules/ps4-waker/dist/waker.js:286:26)
    at /usr/local/lib/node_modules/ps4-waker/dist/detector.js:141:9
    at Detector.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/detector.js:120:26)
    at Detector.emit (events.js:160:13)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/detector.js:61:18)
    at Socket.emit (events.js:160:13)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)`

**Comment by dhleong** [comment]
https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#ps4-waker-can-put-the-ps4-to-sleep-but-not-wake-it-up
