### ISSUE TITLE
Not a PS4-Waker bug, but need guidance

### ISSUE THREAD

**Issue by rickalm** [dhleong/ps4-waker#81]
On my RPi 

apt install npm
npm install ps4-waker -g

pi# node --version
v0.10.29

pi# ps4-waker

/usr/local/lib/node_modules/ps4-waker/bin/cmd.js:3
var {Detector, Device, Socket} = require('../')
    ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

What am i missing

**Comment by dhleong** [comment]
https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#syntaxerror-unexpected-token-error

**Comment by rickalm** [comment]
Thanks, I fell for the old story 0.10.29 oh that must mean 10.29 like other products like Kafka

Warning for anyone attempting to use this on a RaspberryPI, nodejs is WAY old on that distro
