### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by theloading123** [dhleong/ps4-waker#87]
Everytime i try to launch "Homebridge" this message shows up, and i don't know what to do. Please help!!
i only have these plugins:
cmd-switch2
ps4-waker

Does anybody knows what to do?

C:\WINDOWS\system32>homebridge
[2018-8-19 16:52:36] Loaded plugin: homebridge-cmdswitch2
[2018-8-19 16:52:36] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[2018-8-19 16:52:36] ---
[2018-8-19 16:52:36] Loaded config.json with 1 accessories and 1 platforms.
[2018-8-19 16:52:36] ---
[2018-8-19 16:52:36] Loading 1 platforms...
[2018-8-19 16:52:36] [CMD Switch] Initializing cmdSwitch2 platform...
[2018-8-19 16:52:36] Loading 1 accessories...
C:\Users\*********\AppData\Roaming\npm\node_modules\homebridge\lib\api.js:50
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (C:\Users\*******\AppData\Roaming\npm\node_modules\homebridge\lib\api.js:50:12)
    at Server._loadAccessories (C:\Users\*******\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:264:42)
    at Server.run (C:\Users\********\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:86:38)
    at module.exports (C:\Users\********\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:40:10)
    at Object.<anonymous> (C:\Users\*********\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by dhleong** [comment]
Looks like an error in homebridge, not `ps4-waker`. Have you tried asking them about it?

**Comment by theloading123** [comment]
@dhleong actually no... because when i remove the plugin off, homebridge starts normally, but when i put ps4-waker back, it crashes...

**Comment by dhleong** [comment]
I understand that, but the stacktrace of the error there shows that the problem lies in homebridge's code. I have no idea how they're using `ps4-waker` so there's no way for me to debug this.
