### ISSUE TITLE
PS4 Waker and CMD Switch Fails to check status or turn off?

### ISSUE THREAD

**Issue by thanosbetyping** [dhleong/ps4-waker#88]
I've got PS4-Waker installed and when I type 'ps4=waker' into the command line the PS4 turns on. When I type 'ps4-waker standby' it goes into standby.

However, when I run it in home bridge it fails. It seems to be failing to get current state (on/off) and it won't turn off.

When I go to turn it off I get this error;

Login error: LOGIN_FAILED
{ Error: Unable to go standby:11
    at Ps4Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:265:29)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Ps4Socket._ (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:480:14)
    at Ps4Socket.receiveData (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:282:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) status: 11 }

Any ideas?

Also - homebridge shoes this error over and over;

[2018-9-10 08:45:50] [CMD Switch] Failed to determine PS4 Pro state.
[2018-9-10 08:45:50] [CMD Switch] Could not detect any matching PS4 device

Thank you!

**Comment by thanosbetyping** [comment]
Sorry; here is the code in the config.json;

{

             "platform": "cmdSwitch2",
             "name": "CMD Switch",
             "switches": [{
               "name" : "PS4 Pro",
               "on_cmd": "ps4-waker",
               "off_cmd": "ps4-waker standby",
               "state_cmd": "ps4-waker search | grep -i '200 Ok'",
               "polling": true,
               "interval": 5,
               "timeout": 2000,
               "manufacturer": "Sony Corporation",
               "model": "CUH-7015B",
               "serial": "032745240457XXXX"
                    }]

**Comment by thanosbetyping** [comment]
More info; https://github.com/luisiam/homebridge-cmdswitch2 <https://github.com/luisiam/homebridge-cmdswitch2>.

Thanks again for a cool plug-in, do you have a donation page?

-Matt

**Comment by dhleong** [comment]
No problem! I don't have a donation page right now, but it'd be cool if instead you donated to UCLA or a similar cause that fights to protect Net Neutrality, without which such projects might not exist ;)

It looks like you're doing the recommended thing from the project, but maybe homebridge is running as a different user than you're running `ps4-waker` with? You could try using the `-c` parameter to specify the path to [`.ps4-wake.credentials.json`](https://github.com/dhleong/ps4-waker/wiki#credentials)

**Comment by thanosbetyping** [comment]
I’ll look into the UCLA donation - great idea, thanks.

There is only 1 user on this Mac mini and I installed it using the sudo line.  How would I use the -c parameter to show the path? Sorry, I’m new to this (obviously - haha).

-Matt

**Comment by dhleong** [comment]
Using `sudo` makes you temporarily the special `root` user, so actually there is another user! Is homebridge also run with `sudo`?

Since you're on a Mac, the file might still be in your normal user home directory, try:

```
ls -al ~/.ps4-wake.credentials.json
```

**Comment by thanosbetyping** [comment]
Hi,

I get this back;

-rw-r--r--  1 root  staff  120 Sep 10 08:25 /Users/admin/.ps4-wake.credentials.json

?
-Matt

**Comment by dhleong** [comment]
So try passing the `-c /Users/admin/.ps4-wake.credentials.json` parameter to your invocation of `ps4-waker` in that config file.

If that doesn't work, but `ps4-waker` works fine when you invoke it directly, you'll probably get more help out of the homebridge folks

**Comment by thanosbetyping** [comment]
Thanks - I’m not sure how to “pass the -c …” :) So I’ll see what the home bridge folks say as I can turn it on and put it back into standby using the ps4-waker function. It’s the checking the status of the PS4 that isn’t working.

Also - do you happen to know where I can hire someone to help me with some of this type of stuff?

Thanks again!

-Matt

**Comment by dhleong** [comment]
>  I’m not sure how to “pass the -c …” :) 

Just change the line: 

    "state_cmd": "ps4-waker search | grep -i '200 Ok'",

to read:

    "state_cmd": "ps4-waker -c /Users/admin/.ps4-wake.credentials.json search | grep -i '200 Ok'",

**Comment by thanosbetyping** [comment]
Hmmm … I solved my timeout issue (I think) - thank you!!

But now ps4-waker standby isn’t working;

[2018-9-11 20:30:23] [CMD Switch] Failed to turn off PS4 Pro
[2018-9-11 20:30:23] [CMD Switch] Login error: LOGIN_FAILED
Login error: LOGIN_FAILED
{ Error: Unable to go standby:11
    at Ps4Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:265:29)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Ps4Socket._ (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:480:14)
    at Ps4Socket.receiveData (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:282:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) status: 11 }


When I just try to run ps4-waker standby I get the same error and the PS$ does not go into standby. Also, yes my PS4 has a fixed IP address of 10.0.1.121;

The-Server:~ admin$ ps4-waker standby
WAKEUP sent to device... 10.0.1.121
Logging in...
Login error: LOGIN_FAILED
WAKEUP sent to device... 10.0.1.121
Logging in...
Login error: LOGIN_FAILED
{ Error: Unable to go standby:11
    at Ps4Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:265:29)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Ps4Socket._ (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:480:14)
    at Ps4Socket.receiveData (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:282:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) status: 11 }

I tested the “ps4-waker” to check if it will wakeup the PS4 and it does, but it returns this error - even though the PS4 did indeed wake up.

The-Server:~ admin$ ps4-waker
WAKEUP sent to device... 10.0.1.121
Error: Device didn't wake in time
    at loop (/usr/local/lib/node_modules/ps4-waker/dist/waker.js:286:26)
    at /usr/local/lib/node_modules/ps4-waker/dist/detector.js:141:9
    at Detector.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/detector.js:128:9)
    at emitNone (events.js:106:13)
    at Detector.emit (events.js:208:7)
    at Detector.close (/usr/local/lib/node_modules/ps4-waker/dist/detector.js:87:10)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
The-Server:~ admin$ 

Thanks again for your help - I really appreciate it. I went to donate to UCLA and there are a lot of causes - any one in particular (http://giveto.ucla.edu <http://giveto.ucla.edu/>)? 

-Matt

**Comment by dhleong** [comment]
Oh awkward, I meant to say [ACLU](https://www.aclu.org/), but I don't want to tell you how to spend your money. I've heard [GiveWell](https://www.givewell.org/) is a good way to find a charity that makes the most impact for each dollar.

For your errors, check out [this](https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#error-device-didnt-wake-in-time). It could be as simple as deleting the credentials file and to pair again. You might also just try changing the credentials file owner from root to your user with `sudo chown $(whoami) /Users/admin/.ps4-wake.credentials.json`.

**Comment by thanosbetyping** [comment]
Hi Daniel,

Ahh - ACLU makes sense. I’ll donate there - thanks!

I tried sudo chown $(whoami) /Users/admin/.ps4-wake.credentials.json and that didn’t work.

I also deleted the credential file (.ps4-wake.credentials.json) from the admin folder and re-ran ps4-waker and now I get this error (unless I run with the ’sudo’ in front and then PS4-waker is visible in the second screen app, but I didn’t set it up as I wonder if it is the sudo that’s messing things up?



and PS4-Waker isn’t showing up on the second screen app … 

Also any danger in updating npm?


Thanks Daniel.

-Matt

**Comment by thanosbetyping** [comment]
Also - when I search this comes up; 

The-Server:~ admin$ ps4-waker search
{
  "type": "device",
  "statusLine": "620 Server Standby",
  "statusCode": "620",
  "status": "Standby",
  "host-id": "1234567890AB",
  "host-type": "PS4",
  "host-name": "PS4-Waker",
  "host-request-port": "997",
  "device-discovery-protocol-version": "00020020",
  "address": "10.0.1.100"
(note PS4 I woke at 10.0.1.121 is currently on and note in standby mode as the status says)

Is there a way to have the search only check one IP (10.0.1.121) - since I think that is the probably with the CMD Switch fails to check the status - I have 2 PS4’s in the house on the network?

-Matt

**Comment by dhleong** [comment]
> I also deleted the credential file (.ps4-wake.credentials.json) from the admin folder and re-ran ps4-waker and now I get this error (unless I run with the ’sudo’ in front and then PS4-waker is visible in the second screen app, but I didn’t set it up as I wonder if it is the sudo that’s messing things up?

`sudo` is required for the initial set up, because the required ports we need to listen on are "protected."

> Also any danger in updating npm?

None that I'm aware of!

> Is there a way to have the search only check one IP (10.0.1.121) - since I think that is the probably with the CMD Switch fails to check the status - I have 2 PS4’s in the house on the network?

Aha! That is definitely the problem. By default, `ps4-waker` operates on the first device it finds, which is in this case apparently the wrong one. If you do `ps4-waker -h` you'll get some help output which describes the use of the `-d` flag for specifying a specific device. You'll want to add `-d 10.0.1.121` to all of the commands in your homebridge config, like how you added `-c` earlier. You can probably get rid of `-c` actually, but it shouldn't hurt to keep it.

**Comment by thanosbetyping** [comment]
Thanks again for the help with this - with contuinioatly tinkering I was able to get it working. Thank you!!

I have also looked through the ReadMe but can’t find how to get it to always launch a specific game title when it turns on (in my case I want it to always open GT Sport. Any ideas?

Thanks again for the support.

-Matt

**Comment by dhleong** [comment]
You could try doing like `ps4-waker <whatever-flags-you-used> && ps4-waker <whatever-flags> start <title-id>`. See [the wiki](https://github.com/dhleong/ps4-waker/wiki#title-ids) for figuring out the `<title-id>` for GT Sport.

**Comment by thanosbetyping** [comment]
Hi,

For the title; I am using it this way "ps4-waker start CUSA03220 -c /Users/admin/.ps4-wake.credentials.json -d 10.0.1.121”  -I essentially added the “start CUSA03220” into the code that’s been working perfectly. 

Is that correct? The PS4 still turns on, but it isn’t starting GT Sport, it sits at the screen asking to hit the PS button on a controller (which is what it did before I added the “start CUSA03220”)? Here is the link I’m using to get the title ID: https://store.playstation.com/en-us/product/UP9000-CUSA03220_00-GTSPORTS00000000

Any ideas?

Thanks.

**Comment by dhleong** [comment]
It sounds like `ps4-waker` isn't logging you in fully if you're seeing the
"press PS button" screen? Do you have a pin code set on your account?

**Comment by thanosbetyping** [comment]
Hi - no pin setup for me.

**Comment by dhleong** [comment]
If you run that command directly from the command line, are there any errors logged? Am I correct that you don't get all the way logged in, the device is "just" on?

**Comment by thanosbetyping** [comment]
Hi,

When I run the command line directly this is what terminal says;

The-Server:~ admin$ ps4-waker start CUSA03220 -c /Users/admin/.ps4-wake.credentials.json -d 10.0.1.121
WAKEUP sent to device... 10.0.1.121
Error: Device didn't wake in time
    at loop (/usr/local/lib/node_modules/ps4-waker/dist/waker.js:286:26)
    at /usr/local/lib/node_modules/ps4-waker/dist/detector.js:141:9
    at Detector.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/detector.js:128:9)
    at emitNone (events.js:106:13)
    at Detector.emit (events.js:208:7)
    at Detector.close (/usr/local/lib/node_modules/ps4-waker/dist/detector.js:87:10)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
The-Server:~ admin$ 

The PS4 does turn on and it goes to this screen (which is also the same place it had loaded to before I tried to added the “start CUSA03220” to the code as well), the screen it turns on to;

**Comment by dhleong** [comment]
Aha, okay. Try adding the flag `-t 60000`. This will increase the amount of time `ps4-waker` waits before deciding the device didn't wake up, and gives up attempting to log in. The `60000` number is in milliseconds, so this will make it wait for 60 seconds.

**Comment by thanosbetyping** [comment]
Worked perfect!! Thank you.

-Matt

**Comment by thanosbetyping** [comment]
I spoke too soon. Now ps4-waker does turn on from standby fine, logs in, and automatically launches the game (yay!)… however, now the standby feature doesn’t work?

The-Server:~ admin$ ps4-waker standby -c /Users/admin/.ps4-wake.credentials.json -d 10.0.1.121
WAKEUP sent to device... 10.0.1.121
Logging in...
Login error: LOGIN_FAILED
WAKEUP sent to device... 10.0.1.121
Logging in...
Login error: LOGIN_FAILED
{ Error: Unable to go standby:11
    at Ps4Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:265:29)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Ps4Socket._ (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:480:14)
    at Ps4Socket.receiveData (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:282:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) status: 11 }
The-Server:~ admin$

**Comment by dhleong** [comment]
What do you get when you run `ps4-waker --version`?

**Comment by thanosbetyping** [comment]
Last login: Tue Oct  2 23:11:10 on ttys000
The-Server:~ admin$ ps4-waker --version
1.4.3
The-Server:~ admin$ 




Hi - I get 1.4.3

**Comment by dhleong** [comment]
Huh. That is odd.

You could try deleting the credentials file and re-authenticating, making sure to use the same `-d` flag. It's possible you authenticated with the other PS4 so you have valid credentials, but they're not associated with that specific device?

If that doesn't work, try updating to the latest version (should be version 1.5.1) and try the `standby` command again. It probably won't fix anything, but I think that version may have slightly more helpful logging.

**Comment by thanosbetyping** [comment]
Ok - thanks. I’ll give that a try.

**Comment by thanosbetyping** [comment]
Hi,

I deleted the credentials and re-authenticated and the “ps4-waker standby” DID work the first time, but now I get this error;

Unexpected error:30 / LOGIN_FAILED
{ Error: Unable to go standby:11
    at Ps4Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:270:29)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Ps4Socket._ (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:488:14)
    at Ps4Socket.receiveData (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:287:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) status: 11 }
The-Server:~ admin$ 

If I use the -d with standby;

The-Server:~ admin$ ps4-waker standby -d 192.168.1.230
WAKEUP sent to device... 192.168.1.230
Logging in...
Unexpected error:30 / LOGIN_FAILED
WAKEUP sent to device... 192.168.1.230
Logging in...
Unexpected error:30 / LOGIN_FAILED
{ Error: Unable to go standby:11
    at Ps4Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:270:29)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Ps4Socket._ (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:488:14)
    at Ps4Socket.receiveData (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:287:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) status: 11 }

Same error. (not that I have changed the IP address of the PS4, so I am using the current correct one 192.168.1.230 and that was the IP when I re-credentialed ps4-waker. 

Any thoughts or ideas?

Thank you!

**Comment by dhleong** [comment]
Did you use the `-d`  flag when you did the initial set up? If you don't pass `-d`, `ps4-waker` will talk to the *first device it sees*, which may be different *each time*. So, if you have multiple devices on the network, make sure to pass `-d` with *every* invocation. Try deleting the credentials, use `ps4-waker -d <ip>` to set up, then `ps4-waker standby -d <ip>` later.

**Comment by thanosbetyping** [comment]
Hi,

When I try to run “ps4-waker -d 192.168.1.230” I get this error;

The-Server:~ admin$ ps4-waker -d 192.168.1.230
No credentials; Use the PS4 Second Screen App and try to connect to PS4-Waker
Error: Root permissions required to start PS4 Dummy
    at Dummy.listen (/usr/local/lib/node_modules/ps4-waker/dist/dummy.js:48:28)
    at Waker.requestCredentials (/usr/local/lib/node_modules/ps4-waker/dist/waker.js:228:11)
    at Device.d.on (/usr/local/lib/node_modules/ps4-waker/bin/cmd.js:266:20)
    at emitOne (events.js:116:13)
    at Device.emit (events.js:211:7)
    at Waker.__waker.Waker.on.d (/usr/local/lib/node_modules/ps4-waker/dist/device.js:501:18)
    at emitOne (events.js:116:13)
    at Waker.emit (events.js:211:7)
    at /usr/local/lib/node_modules/ps4-waker/dist/waker.js:135:18
    at ReadFileContext.callback (/usr/local/lib/node_modules/ps4-waker/dist/waker.js:174:29)
The-Server:~ admin$ 

So I assume I need to use “sudo ps4-waker -d 192.168.1.230” correct?

**Comment by dhleong** [comment]
Yes

**Comment by thanosbetyping** [comment]
Hi,

So I did it again;

deleted credential file and then reinstalled its;

The-Server:~ admin$ sudo ps4-waker -d 192.168.1.230
Password:
No credentials; Use the PS4 Second Screen App and try to connect to PS4-Waker
Got credentials!  { 'client-type': 'i',
  'auth-type': 'C',
  'user-credential': '01250cc933c180d509de338ee6a09812a429339634296350600124e471e9967e' }
Go to 'Settings -> Mobile App Connection Settings -> Add Device' on your PS4 to obtain the PIN code.
Pin code> 10172963
Logged into device! Future uses should succeed
The-Server:~ admin$ 

I then did this command it the PS4 went to sleep correctly;

The-Server:~ admin$ ps4-waker standby
WAKEUP sent to device... 192.168.1.230
Logging in...
The-Server:~ admin$ 

I waited for the PS4 to be fully asleep again and then I did this and it DID wake up the PS4 and went to this screen (even with the error);

The-Server:~ admin$ ps4-waker -d 192.168.1.230
WAKEUP sent to device... 192.168.1.230
Error: Device didn't wake in time
    at loop (/usr/local/lib/node_modules/ps4-waker/dist/waker.js:292:26)
    at /usr/local/lib/node_modules/ps4-waker/dist/detector.js:141:9
    at Detector.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/detector.js:128:9)
    at emitNone (events.js:106:13)
    at Detector.emit (events.js:208:7)
    at Detector.close (/usr/local/lib/node_modules/ps4-waker/dist/detector.js:87:10)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
The-Server:~ admin$ 


Screen it went to this;


Is this correct? Or should it go further to the main screen?

Also - the app looks setup correctly in the PS4 settings;


Then;

if I use the PS4 Pro switch on the home kit app - it did go to sleep.

Great!!

Then I turned it back on using the home kit switch and it turned on and loaded the game (GT Sport) - perfect! So far … so good.

However, I waited about 5 minutes and then tried to use the home kit switch to turn it back off - it wouldn’t turn off. Note that the PS4 is in the Gran Tursimo game at this point — if that makes a difference?

Here is my Homebridge config.json file for the PS4;

"platform": "cmdSwitch2",
             "name": "CMD Switch",
             "switches": [{
               "name" : "PS4 Pro",
               "on_cmd": "ps4-waker start CUSA03220 -c /Users/admin/.ps4-wake.credentials.json -d 192.168.1.230 -t 60000",
               "off_cmd": "ps4-waker -c /Users/admin/.ps4-wake.credentials.json -d 192.168.1.230 standby",
               "state_cmd": "ps4-waker -c /Users/admin/.ps4-wake.credentials.json -d 192.168.1.230 search | grep -i '200 Ok'",
               "polling": true,
               "interval": 5,
               "timeout": 2000,
               "manufacturer": "Sony Corporation",
               "model": "CUH-7015B",
               "serial": “03279424045786842"


I also tried this;

"platform": "cmdSwitch2",
             "name": "CMD Switch",
             "switches": [{
               "name" : "PS4 Pro",
               "on_cmd": "ps4-waker start CUSA03220 -c /Users/admin/.ps4-wake.credentials.json -d 192.168.1.230 -t 60000",
               "off_cmd": "ps4-waker -c /Users/admin/.ps4-wake.credentials.json -d 192.168.1.230 standby",
               "state_cmd": "ps4-waker -c /Users/admin/.ps4-wake.credentials.json -d 192.168.1.230 search | grep -i '200 Ok'",
               "polling": true,
               "interval": 5,
               "timeout": 2000,
               "manufacturer": "Sony Corporation",
               "model": "CUH-7015B",
               "serial": “03279424045786842"

Neither our the PS4 into standby mode.

I then tried directly in Terminal and got this;
The-Server:~ admin$ ps4-waker -d 192.168.1.230 standby
WAKEUP sent to device... 192.168.1.230
Logging in...
Unexpected error:30 / LOGIN_FAILED
WAKEUP sent to device... 192.168.1.230
Logging in...
Unexpected error:30 / LOGIN_FAILED
{ Error: Unable to go standby:11
    at Ps4Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:270:29)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Ps4Socket._ (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:488:14)
    at Ps4Socket.receiveData (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:287:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) status: 11 }

and without the -d (i’ve unplugged my other ps4 on the network - so the only one I have on the network now is this ps4-pro)

The-Server:~ admin$ ps4-waker standby
WAKEUP sent to device... 192.168.1.230
Logging in...
Unexpected error:30 / LOGIN_FAILED
WAKEUP sent to device... 192.168.1.230
Logging in...
Unexpected error:30 / LOGIN_FAILED
{ Error: Unable to go standby:11
    at Ps4Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:270:29)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Ps4Socket._ (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:488:14)
    at Ps4Socket.receiveData (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:287:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) status: 11 }


Any idea why the standby function will work once and then stops working?

Thanks again for all your support.

**Comment by thanosbetyping** [comment]
Hmmm. Thanks. 

I also tried after quitting GT Sport and it still fails. If I delete it all and re-add it works once and then stops working. 

Odd.

**Comment by dhleong** [comment]
Wild! Does the PS app have any trouble?

**Comment by dhleong** [comment]
@thanosbetyping Do you happen to have any hardware like a keyboard or mouse plugged into your PS4? #98 has consistently reproduced your error with keyboard and mouse plugged in. If that's the case, feel free to follow along there

**Comment by thanosbetyping** [comment]
Hi,

Still checking the app itself to see if that is the issue (been traveling and haven’t been able to try again). But - Yes, I do have a keyboard plugged in - perhaps that’s the issue. Let me look at that too.

Thank you again.

**Comment by dhleong** [comment]
Okay! So we've figured it out, and you can follow along for updates on that
other issue. The bad news is that I still have no idea why having a
keyboard plugged in would cause a problem....
