### ISSUE TITLE
Unable to issue standby command after waking ps4 up

### ISSUE THREAD

**Issue by karanchaudhri** [dhleong/ps4-waker#98]
I was able to set ps4-waker and it worked fine as I was able to wake up my ps4 using this app.
The problem is once it wakes up and then on screen I get the message "Companion App Disconnected".  After that, if I use this app to make my ps4 go into standby mode or any other function it complains "LOGIN FAILED"

Please find the output below - 
```
ps4-waker -d 192.168.1.107 standby
WAKEUP sent to device... 192.168.1.107
Logging in...
Unexpected error:30 / LOGIN_FAILED
WAKEUP sent to device... 192.168.1.107
Logging in...
Unexpected error:30 / LOGIN_FAILED
{ Error: Unable to go standby:11
    at Ps4Socket.<anonymous> (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:270:29)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Ps4Socket.emit (events.js:211:7)
    at Ps4Socket._ (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:488:14)
    at Ps4Socket.receiveData (/usr/local/lib/node_modules/ps4-waker/dist/ps4socket.js:287:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) status: 11 }
```

**Comment by dhleong** [comment]
Have you followed this? https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#ps4-waker-can-put-the-ps4-to-sleep-but-not-wake-it-up

**Comment by karanchaudhri** [comment]
Yes, I have followed all the troubleshooting steps.

**Comment by dhleong** [comment]
Interesting. I can't reproduce this locally, but #88 is experiencing this specific error as well.

Do you have more than one device on your network by any chance?
If you try to put the PS4 into standby using the PS app in the same situation, does it work?

**Comment by karanchaudhri** [comment]
Yes, I have gone through #88 and it seems like we are having a similar issue. 

And I do not have multiple devices in my network. I have also tried -d <my ps4 ip> option and getting the same error.

Also, after ps4-waker complains about the login error, the ps4 second screen app also reports errors and displays this screen (attaching the screenshot for your reference).
![image](https://user-images.githubusercontent.com/7090475/48108842-bf74a880-e1f9-11e8-9cf6-8b32478c9ef9.png)

But if I use ps4 second screen app alone without using any functionality of ps4-waker, it will work fine. I have tried disconnecting and reconning again. PS4 second screen app works as expected.

Since the issue only occurs only after ps4-waker logs in, and after that even ps4 second screen app fails to log in as the companion app, My best assumption would be that the ps4-waker is not handling login feature gracefully. 

Let me know if you need additional details or any kind of logs from me. I will try my best to help you/community to resolve this bug.

**Comment by dhleong** [comment]
> My best assumption would be that the ps4-waker is not handling login feature gracefully.

That would seem to be the case, though I would've expected such an error to occur consistently. I still haven't reproduced it locally, but I'll see if I can uncover anything.

>  I have tried disconnecting and reconning again. PS4 second screen app works as expected.

What do you mean, exactly? Are these the steps:

1. `ps4-waker` to start the PS4
1. PS4 wakes up and logs in normally
1. `ps4-waker standby` fails with the above error
1. Connect PS app
1. PS app shows "Log in on your PS4 app"
1. Disconnect PS app
1. Connect PS app
1. PS app works

**Comment by dhleong** [comment]
@karanchaudhri How adventurous are you?

I discovered a "logout" packet. Sending it before disconnecting doesn't seem to break anything for me, but I'm hoping you'll help test it on your end before I deploy it more widely.

If you're up for it:

1. Clone this repo using Git (`git clone https://github.com/dhleong/ps4-waker.git`) or [download it as a zip](https://github.com/dhleong/ps4-waker/archive/master.zip) and extract it somewhere
1. Run `npm run build`
1. Use `bin/cmd.js` in place of `ps4-waker` and try to wake and subsequently put your PS4 to sleep

**Comment by karanchaudhri** [comment]
@dhleong I see that you committed changes for sending the logout packet. Thanks for trying to resolve this so quickly. But unfortunately, the issue still persists. 

You might be interested in logs and steps I used to test - 
```
root@karan-server:~/ps4-waker# ./bin/cmd.js
(node:6490) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
WAKEUP sent to device... 192.168.1.107
Logging in...
root@karan-server:~/ps4-waker# ./bin/cmd.js standby
(node:6501) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
WAKEUP sent to device... 192.168.1.107
Logging in...
Unexpected error:30 / LOGIN_FAILED
WAKEUP sent to device... 192.168.1.107
Logging in...
Unexpected error:30 / LOGIN_FAILED
{ Error: Unable to go standby:11
    at Ps4Socket.<anonymous> (/home/karan/ps4-waker/dist/ps4socket.js:273:21)
    at Object.onceWrapper (events.js:273:13)
    at Ps4Socket.emit (events.js:182:13)
    at Ps4Socket._ (/home/karan/ps4-waker/dist/ps4socket.js:484:10)
    at Ps4Socket.receiveData (/home/karan/ps4-waker/dist/ps4socket.js:290:24)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) status: 11 }
```

**Comment by dhleong** [comment]
I just pushed another tweak to try to wait for the result of the logout request. Not very confident it will help, but haven't found anything obvious we're missing yet, and still can't reproduce it on my own machine. 

The latest code also lets you enable super-verbose debugging by using `DEBUG=* bin/cmd.js`. Don't know if it will add anything we don't already know, but it's worth a shot.

Thanks for your help!

**Comment by karanchaudhri** [comment]
Hi @dhleong, The issue still persists after getting the latest changes from the repo.

But, I believe this issue occurs only when you have attached keyboard/mouse to your ps4 when you wake ps4 up using this app.
I have tested ps4-waker multiple times without any keyboard/mouse attached to my ps4 and it worked everytime without any issue.

So, you may be able to replicate this issue after attaching a keyboard/mouse to your ps4.

**Comment by dhleong** [comment]
It took a couple on-off cycles with both keyboard and mouse, but I am now consistently repro'ing this error. I'm not *entirely* sure how to deal with this yet, but I'll poke around.

**Comment by karanchaudhri** [comment]
@dhleong Its good that you are now able to reproduce this error. Let me know if you need any help.

**Comment by dhleong** [comment]
Thanks for your help with the repro @karanchaudhri, I never would have tried that. I'll let you know if there's anything else you can do to help!

Some notes:

- The issue only seems to occur if *we* are the ones to wake the device. If I wake it with the PS app, I can connect and disconnect ps4-waker without a problem. 
- Disconnecting the keyboard shows a similar popup as shown when we disconnect the app. Perhaps keyboards are treated similarly to companion apps? This seems insane, but the keyboard *is* the source of the problems.... I suspect a race condition
- The PS app seems to wait much longer to login once the device is awake than we do
- If I keep the socket connection alive for a while after the device wakes up (instead of quitting right away) we don't seem to encounter the LOGIN_MGR_BUSY error. This could be a red herring though, because I reverted the delay just now and it worked (I disconnected the mouse at some point; maybe both mouse and keyboard need to be connected for consistent repro?)

More experimentation to follow

**Comment by dhleong** [comment]
Okay, I was able to repro the error again by plugging in the mouse *and* the keyboard. Delaying the `close()` does not fix the issue, but there could still be a timing issue (or maybe an ordering wrt `BYE` vs `LOGOUT`?)

**Comment by dhleong** [comment]
Tried delaying `LOGOUT`, and subsequently delaying `BYE` to no avail. `BYE` before `LOGOUT` doesn't make sense because `BYE` requests the server to close the socket...

**Comment by karanchaudhri** [comment]
Did you notice any other difference w.r.t packets being sent from ps4-waker and ps4 second screen app? And may I know how did you figure out which type of packets to send using ps4-waker, Did you decompile ps4 second screen apk and reverse engineered it or you monitored which types of packets are being sent out over the network by the second screen app?

**Comment by dhleong** [comment]
I initially figured out login by a combination of packet sniffing and
pretending to be a PS4 and having the PS app talk to me directly, but once
you're logged in all traffic is encrypted with a sort of public-key crypto
(the details are hazy but it's all in the code). I extracted the app's
public key so I can read what the PS4 is sending back and sign things to
send to the PS4, but because I don't have the PS4's private key, I cannot
encrypt the responses back to the app, which means I have no way of knowing
what it's saying after the initial login step.

A lot of more recent features were discovered by reverse engineering the
old PS app, and the Metal Gear Solid second-screen app (which is slightly
less obfuscated, so that helped).

**Comment by karanchaudhri** [comment]
Thanks, @dhleong for letting me know. I really appreciate all of your hard work you have put into this.
The ps4-waker application is really cool and super useful 👍

**Comment by karanchaudhri** [comment]
Any luck in solving this?

**Comment by dhleong** [comment]
Nope. I'm fairly certain my "close session" procedure is correct (just send
BYE and wait for the server to close the socket) and I haven't found
anything else we should be doing as part of the "start session"
procedure....

**Comment by dhleong** [comment]
Quick status update: I've spent a few hours now combing through the raw smali bytecode from the Android app (the decompiler output for the Login proc class is mostly garbage) and haven't found anything new. It looks like our login and logout procedures are "by the book," as it were.

The only notably different thing we're doing is that we only send our client status packet in response to the server status packet (and once after login success), where the official app seems to send it every 10 seconds regardless of server packets, so long as we've received the handshake and initialized crypto (it's basically on a timer as soon as you open the "session," so the timing of the first packet relative to getting the handshake packet is undefined). I could try something like this next time I have time, but I'm not sure why it would lock up the "login manager...."

**Comment by dhleong** [comment]
I also went back to the bytecode of the login proc and discovered a new packet that the client seems to send with info about the client app, on a successful login. Sending this packet doesn't seem to fix the issue, unfortunately.

Also, I tried using `--skip-login` to wake the PS4 and then login after, but it still gets into LOGIN_MGR_BUSY.

Actually, just now I tried doing `--skip-login` and logging in with the PS app. Lo and behold, the second time I try to login *with the official app* it shows the error! So maybe something in the wake process is causing the login manager to be grumpy?

**Comment by dhleong** [comment]
Huh. Okay just now I woke my PS4 (with keyboard and mouse connected) from rest mode using the Second Screen app, disconnected, then tried to connect again and got  "Login in on your PS4."

@karanchaudhri Can you confirm that if you do this, the PS app is able to connect the second time? If not, it may just be a firmware issue

**Comment by karanchaudhri** [comment]
@dhleong Yes, you are right. If I wake my ps4 using PS app, after disconnecting I was not able to get it to work. I also suspect a firmware issue. Thanks for finding that out.
